import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  FileText, 
  Loader2, 
  UserCheck, 
  UserX, 
  DollarSign, 
  Bed,
  AlertTriangle,
  Clock,
  Download
} from "lucide-react";

interface ShiftReport {
  reportDate: string;
  generatedAt: string;
  generatedBy: string;
  summary: {
    checkInsCompleted: number;
    checkOutsCompleted: number;
    pendingArrivals: number;
    noShows: number;
    currentOccupancy: number;
    occupiedRooms: number;
    totalRooms: number;
    todayRevenue: string;
  };
  roomStatus: {
    clean: number;
    dirty: number;
    occupied: number;
    maintenance: number;
    available: number;
  };
  checkIns: Array<{
    confirmationNumber: string;
    roomId: string;
    checkInTime: string;
  }>;
  checkOuts: Array<{
    confirmationNumber: string;
    roomId: string;
    checkOutTime: string;
  }>;
  pendingArrivalsDetails: Array<{
    confirmationNumber: string;
    status: string;
  }>;
}

export default function ShiftReportPanel() {
  const { data, isLoading, error, refetch } = useQuery<{ report: ShiftReport }>({
    queryKey: ["/api/front-desk/shift-report"]
  });

  const downloadReport = () => {
    if (!data?.report) return;

    const report = data.report;
    const csvContent = [
      "Front Desk Shift Report",
      `Report Date,${new Date(report.reportDate).toLocaleDateString()}`,
      `Generated At,${new Date(report.generatedAt).toLocaleString()}`,
      `Generated By,${report.generatedBy}`,
      "",
      "Summary",
      `Check-ins Completed,${report.summary.checkInsCompleted}`,
      `Check-outs Completed,${report.summary.checkOutsCompleted}`,
      `Pending Arrivals,${report.summary.pendingArrivals}`,
      `No-shows,${report.summary.noShows}`,
      `Current Occupancy,${report.summary.currentOccupancy}%`,
      `Occupied Rooms,${report.summary.occupiedRooms}/${report.summary.totalRooms}`,
      `Today's Revenue,$${report.summary.todayRevenue}`,
      "",
      "Room Status",
      `Clean,${report.roomStatus.clean}`,
      `Dirty,${report.roomStatus.dirty}`,
      `Occupied,${report.roomStatus.occupied}`,
      `Maintenance,${report.roomStatus.maintenance}`,
      `Available,${report.roomStatus.available}`,
      "",
      "Check-ins Today",
      "Confirmation,Room,Time",
      ...report.checkIns.map(ci => `${ci.confirmationNumber},${ci.roomId},${ci.checkInTime ? new Date(ci.checkInTime).toLocaleTimeString() : 'N/A'}`),
      "",
      "Check-outs Today",
      "Confirmation,Room,Time",
      ...report.checkOuts.map(co => `${co.confirmationNumber},${co.roomId},${co.checkOutTime ? new Date(co.checkOutTime).toLocaleTimeString() : 'N/A'}`)
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `shift-report-${new Date().toISOString().split("T")[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="text-center text-destructive">
            <AlertTriangle className="h-8 w-8 mx-auto mb-2" />
            <p>Failed to load shift report</p>
            <Button variant="outline" size="sm" className="mt-2" onClick={() => refetch()}>
              Retry
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  const report = data?.report;
  if (!report) return null;

  return (
    <div className="space-y-6" data-testid="panel-shift-report">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Shift Report
          </h2>
          <p className="text-sm text-muted-foreground">
            {new Date(report.reportDate).toLocaleDateString("en-US", { 
              weekday: "long", 
              year: "numeric", 
              month: "long", 
              day: "numeric" 
            })}
          </p>
        </div>
        <Button onClick={downloadReport} variant="outline" data-testid="button-download-report">
          <Download className="h-4 w-4 mr-2" />
          Download CSV
        </Button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-green-100 dark:bg-green-900/30 rounded-lg">
                <UserCheck className="h-5 w-5 text-green-600 dark:text-green-400" />
              </div>
              <div>
                <p className="text-2xl font-bold">{report.summary.checkInsCompleted}</p>
                <p className="text-xs text-muted-foreground">Check-ins</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-orange-100 dark:bg-orange-900/30 rounded-lg">
                <UserX className="h-5 w-5 text-orange-600 dark:text-orange-400" />
              </div>
              <div>
                <p className="text-2xl font-bold">{report.summary.checkOutsCompleted}</p>
                <p className="text-xs text-muted-foreground">Check-outs</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                <Bed className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              </div>
              <div>
                <p className="text-2xl font-bold">{report.summary.currentOccupancy}%</p>
                <p className="text-xs text-muted-foreground">Occupancy</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-emerald-100 dark:bg-emerald-900/30 rounded-lg">
                <DollarSign className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
              </div>
              <div>
                <p className="text-2xl font-bold">${report.summary.todayRevenue}</p>
                <p className="text-xs text-muted-foreground">Revenue</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Room Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm">Available</span>
                <Badge variant="outline" className="bg-green-50 text-green-700 dark:bg-green-900/30 dark:text-green-400">
                  {report.roomStatus.available}
                </Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Occupied</span>
                <Badge variant="outline" className="bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
                  {report.roomStatus.occupied}
                </Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Clean</span>
                <Badge variant="outline" className="bg-emerald-50 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400">
                  {report.roomStatus.clean}
                </Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Dirty</span>
                <Badge variant="outline" className="bg-amber-50 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400">
                  {report.roomStatus.dirty}
                </Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Maintenance</span>
                <Badge variant="outline" className="bg-red-50 text-red-700 dark:bg-red-900/30 dark:text-red-400">
                  {report.roomStatus.maintenance}
                </Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <Clock className="h-4 w-4" />
              Pending
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm">Arrivals Pending</span>
                <Badge variant="secondary">{report.summary.pendingArrivals}</Badge>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">No-Shows Today</span>
                <Badge variant="destructive">{report.summary.noShows}</Badge>
              </div>
              <Separator className="my-2" />
              <div className="flex justify-between items-center">
                <span className="text-sm font-medium">Total Rooms</span>
                <span className="font-bold">{report.summary.occupiedRooms}/{report.summary.totalRooms}</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {(report.checkIns.length > 0 || report.checkOuts.length > 0) && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {report.checkIns.length > 0 && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <UserCheck className="h-4 w-4 text-green-600" />
                  Check-ins Today ({report.checkIns.length})
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {report.checkIns.map((ci, i) => (
                    <div key={i} className="flex justify-between items-center text-sm p-2 bg-muted rounded">
                      <span className="font-medium">{ci.confirmationNumber}</span>
                      <span className="text-muted-foreground">
                        {ci.checkInTime ? new Date(ci.checkInTime).toLocaleTimeString() : "N/A"}
                      </span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {report.checkOuts.length > 0 && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <UserX className="h-4 w-4 text-orange-600" />
                  Check-outs Today ({report.checkOuts.length})
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {report.checkOuts.map((co, i) => (
                    <div key={i} className="flex justify-between items-center text-sm p-2 bg-muted rounded">
                      <span className="font-medium">{co.confirmationNumber}</span>
                      <span className="text-muted-foreground">
                        {co.checkOutTime ? new Date(co.checkOutTime).toLocaleTimeString() : "N/A"}
                      </span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      <div className="text-xs text-muted-foreground text-center">
        Generated at {new Date(report.generatedAt).toLocaleString()} by {report.generatedBy}
      </div>
    </div>
  );
}
